import '../layout/style'
import '../form/style'
import '../table/style'
import '../scroll/style'
import '../card/style'
import '../button/style'
import '@ui/styles/anime/fade.scss'
import './style.scss'
