// 由 `bun run resolver:gen`（scripts/gen-vite-resolver.ts）生成，请勿手动编辑。

export interface VeltraComponentPackage {
  /** 组件的导入来源包名 */
  from: string
  /** 组件名 → 样式副作用子路径（相对包名，无扩展名） */
  components: Record<string, string>
}

export const VELTRA_COMPONENT_PACKAGES: VeltraComponentPackage[] = [
  {
    from: '@veltra/desktop',
    components: {
      UAction: 'components/action/style',
      UActionGroup: 'components/action/style',
      UAutoComplete: 'components/auto-complete/style',
      UBadge: 'components/badge/style',
      UBatchEdit: 'components/batch-edit/style',
      UBreadcrumb: 'components/breadcrumb/style',
      UButton: 'components/button/style',
      UButtonGroup: 'components/button/style',
      UCalendar: 'components/calendar/style',
      UCard: 'components/card/style',
      UCardAction: 'components/card/style',
      UCardContent: 'components/card/style',
      UCardCover: 'components/card/style',
      UCardHeader: 'components/card/style',
      UCascade: 'components/cascade/style',
      UCheckbox: 'components/checkbox/style',
      UCheckboxButton: 'components/checkbox/style',
      UCheckboxGroup: 'components/checkbox-group/style',
      UCheckTag: 'components/check-tag/style',
      UCodeEditor: 'components/code-editor/style',
      UCollapse: 'components/collapse/style',
      UCollapseItem: 'components/collapse/style',
      UConditionEditor: 'components/condition-editor/style',
      UContextmenu: 'components/contextmenu/style',
      UDatePanel: 'components/date-panel/style',
      UDatePicker: 'components/date-picker/style',
      UDateRangePicker: 'components/date-range-picker/style',
      UDialog: 'components/dialog/style',
      UDrawer: 'components/drawer/style',
      UDropdown: 'components/dropdown/style',
      UDualNav: 'components/dual-nav/style',
      UEmpty: 'components/empty/style',
      UExpressionEditor: 'components/expression-editor/style',
      UFilePicker: 'components/file-picker/style',
      UFileViewer: 'components/file-viewer/style',
      UFloatButton: 'components/float-button/style',
      UForm: 'components/form/style',
      UFormItem: 'components/form-item/style',
      UGanttChart: 'components/gantt-chart/style',
      UGrid: 'components/grid/style',
      UGridInput: 'components/grid-input/style',
      UGridItem: 'components/grid/style',
      UGroupInput: 'components/group-input/style',
      UGroupNav: 'components/group-nav/style',
      UIcon: 'components/icon/style',
      UInput: 'components/input/style',
      UKbd: 'components/kbd/style',
      ULayout: 'components/layout/style',
      UList: 'components/list/style',
      UListItem: 'components/list/style',
      ULoading: 'components/loading/style',
      UMessage: 'components/message/style',
      UMessageConfirm: 'components/message-confirm/style',
      UMultiSelect: 'components/multi-select/style',
      UMultiTreeSelect: 'components/multi-tree-select/style',
      UNav: 'components/nav/style',
      UNavItem: 'components/nav/style',
      UNavSub: 'components/nav/style',
      UNodeRender: 'components/node-render/style',
      UNotification: 'components/notification/style',
      UNumber: 'components/number/style',
      UNumberInput: 'components/number-input/style',
      UNumberRangeInput: 'components/number-range-input/style',
      UPaginator: 'components/paginator/style',
      UPalette: 'components/palette/style',
      UPasswordInput: 'components/password-input/style',
      UPopConfirm: 'components/pop-confirm/style',
      UProgress: 'components/progress/style',
      UProgressNodes: 'components/progress-nodes/style',
      URadio: 'components/radio/style',
      URadioGroup: 'components/radio-group/style',
      URichTextEditor: 'components/rich-text-editor/style',
      UScroll: 'components/scroll/style',
      USelect: 'components/select/style',
      USlider: 'components/slider/style',
      USteps: 'components/steps/style',
      USwitch: 'components/switch/style',
      UTable: 'components/table/style',
      UTableEditor: 'components/table-editor/style',
      UTabs: 'components/tabs/style',
      UTabsHorizontal: 'components/tabs/style',
      UTabsVertical: 'components/tabs/style',
      UTag: 'components/tag/style',
      UText: 'components/text/style',
      UTextarea: 'components/textarea/style',
      UTheme: 'components/theme/style',
      UTip: 'components/tip/style',
      UTree: 'components/tree/style',
      UTreeSelect: 'components/tree-select/style',
      UWatermark: 'components/watermark/style'
    }
  },
  { from: '@veltra/ai', components: { UAiChat: 'components/ai-chat/style' } },
  {
    from: '@veltra/sheet',
    components: {
      UReportDesigner: 'components/report/style',
      UReportViewer: 'components/report/style',
      USheet: 'components/sheet/style'
    }
  }
]
