import type { ComponentResolver } from 'unplugin-vue-components/types'

import { VELTRA_COMPONENT_PACKAGES } from './components.gen'

export interface VeltraUIResolverOptions {
  /**
   * Whether to import component styles as side effects.
   * @default true
   */
  importStyle?: boolean
}

interface ComponentEntry {
  from: string
  style: string
}

const COMPONENTS: ReadonlyMap<string, ComponentEntry> = new Map(
  VELTRA_COMPONENT_PACKAGES.flatMap(({ components, from }) =>
    Object.entries(components).map(
      ([name, stylePath]) => [name, { from, style: `${from}/${stylePath}` }] as const
    )
  )
)

/**
 * Resolver for `unplugin-vue-components` that auto-imports Veltra UI components
 * (`@veltra/desktop`, `@veltra/ai`, `@veltra/sheet`) and their style side effects.
 *
 * The component table lives in `components.gen.ts`, regenerated by
 * `bun run resolver:gen` whenever those packages gain or drop a component.
 *
 * Style resolution relies on each package's exports conditions:
 * - **veltra-dev** (Vite dev): resolves to `src/<dir>/style.ts`
 *   (source SCSS pipeline, full HMR)
 * - **import** (Vite build): resolves to `dist/<dir>/style.js`
 *   (pre-compiled, CSS imported by the JS entry)
 */
export function VeltraUIResolver(options: VeltraUIResolverOptions = {}): ComponentResolver {
  const { importStyle = true } = options

  return {
    type: 'component',
    resolve(name: string) {
      const component = COMPONENTS.get(name)
      if (!component) return

      return { name, from: component.from, sideEffects: importStyle ? component.style : undefined }
    }
  }
}
