/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAction: typeof import('ultra-ui')['UAction']
    UActionGroup: typeof import('ultra-ui')['UActionGroup']
    UAutoComplete: typeof import('ultra-ui')['UAutoComplete']
    UBatchEdit: typeof import('ultra-ui')['UBatchEdit']
    UButton: typeof import('ultra-ui')['UButton']
    UButtonGroup: typeof import('ultra-ui')['UButtonGroup']
    UCard: typeof import('ultra-ui')['UCard']
    UCardContent: typeof import('ultra-ui')['UCardContent']
    UCardHeader: typeof import('ultra-ui')['UCardHeader']
    UCascade: typeof import('ultra-ui')['UCascade']
    UCheckbox: typeof import('ultra-ui')['UCheckbox']
    UDatePicker: typeof import('ultra-ui')['UDatePicker']
    UDialog: typeof import('ultra-ui')['UDialog']
    UDropdown: typeof import('ultra-ui')['UDropdown']
    UForm: typeof import('ultra-ui')['UForm']
    UGroupInput: typeof import('ultra-ui')['UGroupInput']
    UInput: typeof import('ultra-ui')['UInput']
    UMenu: typeof import('ultra-ui')['UMenu']
    UMenuItemCollapsed: typeof import('ultra-ui')['UMenuItemCollapsed']
    UMenuSubCollapsed: typeof import('ultra-ui')['UMenuSubCollapsed']
    UMultiSelect: typeof import('ultra-ui')['UMultiSelect']
    UMultiTreeSelect: typeof import('ultra-ui')['UMultiTreeSelect']
    UNumberInput: typeof import('ultra-ui')['UNumberInput']
    UPasswordInput: typeof import('ultra-ui')['UPasswordInput']
    URadio: typeof import('ultra-ui')['URadio']
    URadioGroup: typeof import('ultra-ui')['URadioGroup']
    UScroll: typeof import('ultra-ui')['UScroll']
    USelect: typeof import('ultra-ui')['USelect']
    UTable: typeof import('ultra-ui')['UTable']
    UTextarea: typeof import('ultra-ui')['UTextarea']
    UTextEditor: typeof import('ultra-ui')['UTextEditor']
    UTip: typeof import('ultra-ui')['UTip']
    UTop: typeof import('ultra-ui')['UTop']
    UTreeSelect: typeof import('ultra-ui')['UTreeSelect']
  }
}
