/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAction: typeof import('ultra-ui')['UAction']
    UActionGroup: typeof import('ultra-ui')['UActionGroup']
    UAutoComplete: typeof import('ultra-ui')['UAutoComplete']
    UBadge: typeof import('ultra-ui')['UBadge']
    UBatchEdit: typeof import('ultra-ui')['UBatchEdit']
    UButton: typeof import('ultra-ui')['UButton']
    UButtonGroup: typeof import('ultra-ui')['UButtonGroup']
    UCard: typeof import('ultra-ui')['UCard']
    UCardAction: typeof import('ultra-ui')['UCardAction']
    UCardContent: typeof import('ultra-ui')['UCardContent']
    UCardCover: typeof import('ultra-ui')['UCardCover']
    UCardHeader: typeof import('ultra-ui')['UCardHeader']
    UCascade: typeof import('ultra-ui')['UCascade']
    UCheckbox: typeof import('ultra-ui')['UCheckbox']
    UCheckboxGroup: typeof import('ultra-ui')['UCheckboxGroup']
    UDatePicker: typeof import('ultra-ui')['UDatePicker']
    UDialog: typeof import('ultra-ui')['UDialog']
    UInput: typeof import('ultra-ui')['UInput']
    UMultiSelect: typeof import('ultra-ui')['UMultiSelect']
    UMultiTreeSelect: typeof import('ultra-ui')['UMultiTreeSelect']
    UNumberInput: typeof import('ultra-ui')['UNumberInput']
    URadio: typeof import('ultra-ui')['URadio']
    URadioGroup: typeof import('ultra-ui')['URadioGroup']
    UScroll: typeof import('ultra-ui')['UScroll']
    USelect: typeof import('ultra-ui')['USelect']
    USteps: typeof import('ultra-ui')['USteps']
    UTable: typeof import('ultra-ui')['UTable']
    UText: typeof import('ultra-ui')['UText']
    UTree: typeof import('ultra-ui')['UTree']
    UTreeSelect: typeof import('ultra-ui')['UTreeSelect']
  }
}
