/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UBatchEdit: typeof import('ultra-ui')['UBatchEdit']
    UButton: typeof import('ultra-ui')['UButton']
    UCard: typeof import('ultra-ui')['UCard']
    UCardContent: typeof import('ultra-ui')['UCardContent']
    UCardHeader: typeof import('ultra-ui')['UCardHeader']
    UCheckbox: typeof import('ultra-ui')['UCheckbox']
    UDialog: typeof import('ultra-ui')['UDialog']
    UInput: typeof import('ultra-ui')['UInput']
    UNumberInput: typeof import('ultra-ui')['UNumberInput']
    URadio: typeof import('ultra-ui')['URadio']
    URadioGroup: typeof import('ultra-ui')['URadioGroup']
    UScroll: typeof import('ultra-ui')['UScroll']
    UTextarea: typeof import('ultra-ui')['UTextarea']
    UTip: typeof import('ultra-ui')['UTip']
  }
}
