import '../layout/style'
import '../form/style'
import '../table/style'
import '../scroll/style'
import '../card/style'
import '../checkbox/style'
import '../tip/style'
import '../button/style'
import '../action/style'
import '@ultra-ui/directives'
import '../../styles/anime/fade.scss'
import './style.scss'
// import './style-new.scss'
