import '../layout/style'
import '../form/style'
import '../table/style'
import '../scroll/style'
import '../card/style'
import '../checkbox/style'
import '../tip/style'
import '../button/style'
import '../action/style'
import '@veltra/directives/ripple/style.js'
import '@veltra/styles/anime/fade.scss'
import './style.scss'
// import './style-new.scss'
