/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAutoComplete: typeof import('@veltra/desktop')['UAutoComplete']
    UButton: typeof import('@veltra/desktop')['UButton']
    UButtonGroup: typeof import('@veltra/desktop')['UButtonGroup']
    UCard: typeof import('@veltra/desktop')['UCard']
    UCardContent: typeof import('@veltra/desktop')['UCardContent']
    UCardHeader: typeof import('@veltra/desktop')['UCardHeader']
    UDrawer: typeof import('@veltra/desktop')['UDrawer']
    UDualNav: typeof import('@veltra/desktop')['UDualNav']
    UIcon: typeof import('@veltra/desktop')['UIcon']
    URadioGroup: typeof import('@veltra/desktop')['URadioGroup']
    UScroll: typeof import('@veltra/desktop')['UScroll']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UAutoComplete: typeof import('@veltra/desktop')['UAutoComplete']
  const UButton: typeof import('@veltra/desktop')['UButton']
  const UButtonGroup: typeof import('@veltra/desktop')['UButtonGroup']
  const UCard: typeof import('@veltra/desktop')['UCard']
  const UCardContent: typeof import('@veltra/desktop')['UCardContent']
  const UCardHeader: typeof import('@veltra/desktop')['UCardHeader']
  const UDrawer: typeof import('@veltra/desktop')['UDrawer']
  const UDualNav: typeof import('@veltra/desktop')['UDualNav']
  const UIcon: typeof import('@veltra/desktop')['UIcon']
  const URadioGroup: typeof import('@veltra/desktop')['URadioGroup']
  const UScroll: typeof import('@veltra/desktop')['UScroll']
}